"use strict";

//ANSWERS
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("answers", [
      //QUESTION ID 1
      {
        answer:
          "Es una librería front-end. Basada en el lenguaje JavaScript, creada por Facebook.",
        value: true,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es una librería back-end.",
        value: false,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es una libreria para aplicaciones moviles",
        value: false,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es un framework, como Bootstrap",
        value: false,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es una extension de JavaScript",
        value: false,
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 2
      {
        answer: "Acrónimo de JavaScript XML",
        value: true,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Acrónimo de JavaScriptXugar",
        value: false,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Una nueva libreria de JS",
        value: false,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Un nuevo lenguaje de programacion",
        value: false,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lo que viene a remplazar a JS",
        value: false,
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 3
      {
        answer: "Funciones JS, reutilizables cuando se necesiten",
        value: true,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Prototypes de Classes",
        value: false,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Funciones recursivas",
        value: false,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lo mismo que un reducer en React-Redux",
        value: false,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Un store que guarda todos los estados de la aplicacion",
        value: false,
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 4
      {
        answer:
          "componentWillMount(), componentDidMount(), componentWillUnmount(), etc",
        value: true,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer:
          "componentWillMount(), componentWillDesmontar, componentMontado(), etc",
        value: false,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer:
          "componentMontado(), componentWillUnmount(), componentDesmontado(), etc",
        value: false,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer:
          "componentMontado(), componentWillMountar(), componentStateToProps(), etc",
        value: false,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer:
          "componentWillMountUnmount(), componentWillDesmount(), componentStateToProps(), etc",
        value: false,
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 5
      {
        answer:
          "React está enfocado al desarrollo de sitios web, mientras que React Native sirve para desarrollo aplicaciones multiplataforma o app híbridas",
        value: true,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son lo mismo",
        value: false,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Solo el nombre",
        value: false,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "ReactJS es para moviles y React Native para sitios web",
        value: false,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Uno ya no se usa mas, y el otro vino a remplazarlo",
        value: false,
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 6
      {
        answer:
          "Los componentes contenedores, se enfocan en proporcionar logica a la presentación, y los componentes de presentación, son responsables del aspecto visual",
        value: true,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son lo mismo",
        value: false,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Solo el nombre",
        value: false,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Solo se usan los de presentación",
        value: false,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "En los contenedores no se puede escribir logica",
        value: false,
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 7
      {
        answer:
          "Hooks son una nueva característica en React 16.8. Estos te permiten usar el estado y otras características de React sin escribir una clase.",
        value: true,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Eso no existe en React",
        value: false,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son una forma nueva de crear estilos",
        value: false,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es una forma de interactuar con el DOM",
        value: false,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer:
          "Son funciones nativas de React enfocadas en la forma en que escribimos codigo",
        value: false,
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 8
      {
        answer:
          "Si hablamos acerca de un solo elemento, entonces render() lo devuelve. Sin embargo, cuando tratamos con elementos múltiples, tendrían que agruparse para hacerlo",
        value: true,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Eso no existe en React",
        value: false,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Sirve para renderizar solo imagenes en React",
        value: false,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es un nuevo Hook",
        value: false,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Remplaza al componentDidMount",
        value: false,
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 9
      {
        answer:
          "Los estados son objetos que contienen ciertos datos dentro de ellos, y pueden alterarse durante los ciclos de vida del componente",
        value: true,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Eso no existe en React",
        value: false,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Hace referencia a si el componente esta montado o no",
        value: false,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es un nuevo Hook",
        value: false,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Es una funcion nativa de JavaScript",
        value: false,
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 10
      {
        answer:
          "Props, significa propiedades. Los componentes principales le brindan props a los componentes secundarios para de esta forma mantener el cuadro de la aplicación",
        value: true,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son los estilos CSS de un componente",
        value: false,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son los estados locales de un componente de presentación",
        value: false,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son un nuevo Hook",
        value: false,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Son propiedades nativas que vienen con los Hooks",
        value: false,
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 11
      {
        answer:
          "Angular es un lenguaje front-end de código abierto basado en TypeScript que facilita la creación de aplicaciones en la web / móvil y de escritorio.",
        value: true,
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 12
      {
        answer:
          "AngularJS usa JavaScript como lenguaje, mientras que Angular esta basado en TypeScript",
        value: true,
        questionId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 13
      {
        answer:
          "Las directivas añaden comportamiento a un elemento del DOM existente.",
        value: true,
        questionId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 14
      {
        answer:
          "Es una interfaz de línea de comando para montar y construir aplicaciones de Angular.",
        value: true,
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 15
      {
        answer:
          "La interpolación es una sintaxis especial de Angular, que permite hacer binding de una propiedad",
        value: true,
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 16
      {
        answer:
          "Angular es un lenguaje front-end de código abierto basado en TypeScript que facilita la creación de aplicaciones en la web / móvil y de escritorio",
        value: true,
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 17
      {
        answer:
          "AngularJS usa JavaScript como lenguaje, mientras que Angular esta basado en TypeScript",
        value: true,
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 18
      {
        answer:
          "Las directivas añaden comportamiento a un elemento del DOM existente",
        value: true,
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 19
      {
        answer:
          "Es una interfaz de línea de comando para montar y construir aplicaciones de Angular",
        value: true,
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 20
      {
        answer:
          "La interpolación es una sintaxis especial de Angular, que permite hacer binding de una propiedad",
        value: true,
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 21
      {
        answer:
          "Java es un lenguaje de programación de alto nivel, multi-plataforma. Es una colección de objetos desarrollado por Sun Microsystems",
        value: true,
        questionId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 21,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 22
      {
        answer: "Los IDE de JAVA son: Eclipse y NetBeans",
        value: true,
        questionId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 23
      {
        answer:
          "Una clase tiene variables y métodos y está integrada por códigos",
        value: true,
        questionId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 23,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 24
      {
        answer: "El Polimorfismo significa que tiene muchas formas",
        value: true,
        questionId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 25
      {
        answer:
          "La anulación del método se produce si el método de subclase satisface las  condiciones con el método de Super clase",
        value: true,
        questionId: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 26
      {
        answer:
          "Python, es un lenguaje de programación de alto nivel con características integradas de administración de memoria, threads, strings",
        value: true,
        questionId: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 27
      {
        answer:
          "El lenguaje Python posee cinco tipos diferentes de datos: string, lista, número, diccionario y tuple",
        value: true,
        questionId: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 27,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 28
      {
        answer:
          "La lista es mucho más lenta, pero puede ser editada, mientras que los tuples trabajan más rápido, pero no pueden ser modificados",
        value: true,
        questionId: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 29
      {
        answer:
          "Pass, simplemente indica un espacio que debería quedar en blanco dentro de la declaración compound",
        value: true,
        questionId: 29,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 29,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 29,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 29,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 29,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      //QUESTION ID 30
      {
        answer:
          "Lambda, es una función ejecutada anonimamente con solo una, única expresión",
        value: true,
        questionId: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Nullam lorem nisl, condimentum at commodo quis",
        value: false,
        questionId: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        value: false,
        questionId: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Quisque eget magna tristique, condimentum sapien eu",
        value: false,
        questionId: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: "Maecenas nec sodales neque, in suscipit mi",
        value: false,
        questionId: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("answers", null, {});
  },
};
